name: 'Retrieve memory info'
description: 'Retrieve the memory infos from the OS'
inputs:
  myInput:  # id of input
    description: 'Greeting man'
    required: true
    default: 'Awesome lab'
outputs:
  myOutput: # id of output
    description: 'The total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
