name: 'Retrieve memory info'
description: 'Retrieve the memory infos from the OS'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  memory: # id of output
    description: 'The memory info we wanted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
