on: [push]
  
jobs:
  memory_retrieve_job:
    runs-on: ubuntu-latest
    name: Retrieve memory info
    steps:
      - uses: actions/checkout@v2
      - name: run action step
        id: hello
        uses: ./
        with:
          myInput: 'Boris Tibago'
      - name: output
        run:  |
          echo ${{ steps.hello.outputs.memory }}
          echo "The total memory successfully output"
